In [145]:
import pandas as pd


In [146]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [147]:
movies=pd.read_csv('dataset.csv')
movies.head()

,Id,Title,Genres,Popularity,Release Date,Original Language,Vote Average,Vote Count,Overview
0,155,The Dark Knight,"['Drama', 'Action', 'Crime', 'Thriller']",82.214,2008-07-14,en,8.510,30011,Batman raises the stakes in his war on crime. ...
1,122,The Lord of the Rings: The Return of the King,"['Adventure', 'Fantasy', 'Action']",74.454,2003-12-01,en,8.477,21810,Aragorn is revealed as the heir to the ancient...
2,569094,Spider-Man: Across the Spider-Verse,"['Action', 'Adventure', 'Animation', 'Science ...",1648.384,2023-05-31,en,8.530,2110,"After reuniting with Gwen Stacy, Brooklyn’s ..."
3,27205,Inception,"['Action', 'Science Fiction', 'Adventure']",86.087,2010-07-15,en,8.363,33958,"Cobb, a skilled thief who commits corporate es..."
4,120,The Lord of the Rings: The Fellowship of the Ring,"['Adventure', 'Fantasy', 'Action']",91.459,2001-12-18,en,8.400,22920,"Young hobbit Frodo Baggins, after inheriting a..."


In [148]:
movies.describe()


,Id,Popularity,Vote Average,Vote Count
count,2.424000e+03,2424.000000,2424.000000,2424.000000
mean,1.445358e+05,39.923460,7.069005,3293.403465
std,2.261117e+05,163.406766,1.121598,4475.363676
min,1.100000e+01,0.600000,0.000000,0.000000
25%,3.671000e+03,11.080750,6.804000,631.000000
50%,1.283000e+04,17.325000,7.202500,1492.500000
75%,2.497090e+05,31.149000,7.597000,3900.750000
max,1.130515e+06,3963.447000,10.000000,33958.000000


In [149]:
movies.info()

<class 'pandas.DataFrame'>
RangeIndex: 2424 entries, 0 to 2423
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Id                 2424 non-null   int64  
 1   Title              2424 non-null   str    
 2   Genres             2424 non-null   str    
 3   Popularity         2424 non-null   float64
 4   Release Date       2419 non-null   str    
 5   Original Language  2424 non-null   str    
 6   Vote Average       2424 non-null   float64
 7   Vote Count         2424 non-null   int64  
 8   Overview           2422 non-null   str    
dtypes: float64(2), int64(2), str(5)
memory usage: 170.6 KB


In [150]:
movies.isnull().sum()

Id                   0
Title                0
Genres               0
Popularity           0
Release Date         5
Original Language    0
Vote Average         0
Vote Count           0
Overview             2
dtype: int64

In [151]:
movies.columns


Index(['Id', 'Title', 'Genres', 'Popularity', 'Release Date',
       'Original Language', 'Vote Average', 'Vote Count', 'Overview'],
      dtype='str')

In [152]:
#our recommeder systen does not need orginal language ,release date ,popularity ,vote avg and vote count 
#  so we will drop these columns

#we need only movie id, title ,genre, overview 

In [153]:
#movies=movies.drop(columnts =['original_language','release_date','popularity','vote_average','vote_count'],axis=1)

In [154]:
movies=movies[['Id','Title','Genres','Overview']]

In [155]:
movies.head()

,Id,Title,Genres,Overview
0,155,The Dark Knight,"['Drama', 'Action', 'Crime', 'Thriller']",Batman raises the stakes in his war on crime. ...
1,122,The Lord of the Rings: The Return of the King,"['Adventure', 'Fantasy', 'Action']",Aragorn is revealed as the heir to the ancient...
2,569094,Spider-Man: Across the Spider-Verse,"['Action', 'Adventure', 'Animation', 'Science ...","After reuniting with Gwen Stacy, Brooklyn’s ..."
3,27205,Inception,"['Action', 'Science Fiction', 'Adventure']","Cobb, a skilled thief who commits corporate es..."
4,120,The Lord of the Rings: The Fellowship of the Ring,"['Adventure', 'Fantasy', 'Action']","Young hobbit Frodo Baggins, after inheriting a..."


In [156]:
#merging genres and overview to crete column called tag 

In [157]:
movies['tags']=movies['Genres']+' '+movies['Overview']
movies.head()

,Id,Title,Genres,Overview,tags
0,155,The Dark Knight,"['Drama', 'Action', 'Crime', 'Thriller']",Batman raises the stakes in his war on crime. ...,"['Drama', 'Action', 'Crime', 'Thriller'] Batma..."
1,122,The Lord of the Rings: The Return of the King,"['Adventure', 'Fantasy', 'Action']",Aragorn is revealed as the heir to the ancient...,"['Adventure', 'Fantasy', 'Action'] Aragorn is ..."
2,569094,Spider-Man: Across the Spider-Verse,"['Action', 'Adventure', 'Animation', 'Science ...","After reuniting with Gwen Stacy, Brooklyn’s ...","['Action', 'Adventure', 'Animation', 'Science ..."
3,27205,Inception,"['Action', 'Science Fiction', 'Adventure']","Cobb, a skilled thief who commits corporate es...","['Action', 'Science Fiction', 'Adventure'] Cob..."
4,120,The Lord of the Rings: The Fellowship of the Ring,"['Adventure', 'Fantasy', 'Action']","Young hobbit Frodo Baggins, after inheriting a...","['Adventure', 'Fantasy', 'Action'] Young hobbi..."


In [158]:
movies=movies.drop(columns=['Genres','Overview'])
movies.head()

,Id,Title,tags
0,155,The Dark Knight,"['Drama', 'Action', 'Crime', 'Thriller'] Batma..."
1,122,The Lord of the Rings: The Return of the King,"['Adventure', 'Fantasy', 'Action'] Aragorn is ..."
2,569094,Spider-Man: Across the Spider-Verse,"['Action', 'Adventure', 'Animation', 'Science ..."
3,27205,Inception,"['Action', 'Science Fiction', 'Adventure'] Cob..."
4,120,The Lord of the Rings: The Fellowship of the Ring,"['Adventure', 'Fantasy', 'Action'] Young hobbi..."


In [159]:
# text data -- nlp concepts 
#2 ways : bag of words and tfidf vectorizer


we using BOW

In production recommender systems they often try multiple approaches:

Bag of Words
TF-IDF
Word2Vec
BERT embeddings

Then compare similarity results

In [160]:
from sklearn.feature_extraction.text import CountVectorizer
#to convert text into vector
cv=CountVectorizer(max_features=5000 ,stop_words='english')
cv.fit_transform(movies['tags'].astype('U')).toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(2424, 5000))

In [161]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf=TfidfVectorizer(max_features=5000,stop_words='english')
vector=tfidf.fit_transform(movies['tags'].values.astype('U')).toarray()
vector


array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], shape=(2424, 5000))

In [162]:
from sklearn.metrics.pairwise import cosine_similarity
sim=cosine_similarity(vector)
sim

array([[1.        , 0.00546308, 0.00448245, ..., 0.00364324, 0.02348473,
        0.        ],
       [0.00546308, 1.        , 0.02833291, ..., 0.01382365, 0.01249583,
        0.01151486],
       [0.00448245, 0.02833291, 1.        , ..., 0.05194813, 0.        ,
        0.01770974],
       ...,
       [0.00364324, 0.01382365, 0.05194813, ..., 1.        , 0.01949842,
        0.01796772],
       [0.02348473, 0.01249583, 0.        , ..., 0.01949842, 1.        ,
        0.05321066],
       [0.        , 0.01151486, 0.01770974, ..., 0.01796772, 0.05321066,
        1.        ]], shape=(2424, 2424))

In [163]:
movies['Title'].values[2]

'Spider-Man: Across the Spider-Verse'

In [164]:
movies[movies['Title']=='The Dark Knight Rises']

,Id,Title,tags
20,49026,The Dark Knight Rises,"['Action', 'Crime', 'Drama', 'Thriller'] Follo..."


In [165]:
movies[movies['Title']=='The Dark Knight Rises'].index[0]

20

In [166]:
sim[2]

array([0.00448245, 0.02833291, 1.        , ..., 0.05194813, 0.        ,
       0.01770974], shape=(2424,))

In [167]:
#ab isko enumerate krdenge kyuki we want to find top 5 results ,enumerate isko sbke sath iterate krdeg
sorted(list (enumerate(sim[2])),reverse=True)
#here sorting is basd on index [0]
sorted(list(enumerate(sim[2])),reverse=True,key=lambda x:x[1])
#now it will sort by index[1] jo ki sim_score h

[(2, np.float64(1.0)),
 (17, np.float64(0.42270488818560925)),
 (287, np.float64(0.20637643102698372)),
 (38, np.float64(0.17411871256445144)),
 (2187, np.float64(0.15608125533549166)),
 (111, np.float64(0.12345426565212533)),
 (293, np.float64(0.12312550570432182)),
 (2296, np.float64(0.11973000030910241)),
 (769, np.float64(0.10859863818609797)),
 (836, np.float64(0.10462848651524495)),
 (763, np.float64(0.10433043099675286)),
 (631, np.float64(0.10258126468610797)),
 (564, np.float64(0.10150576379036373)),
 (137, np.float64(0.1006448370789942)),
 (831, np.float64(0.09802065842437375)),
 (1599, np.float64(0.09788615689788366)),
 (21, np.float64(0.09709797093080809)),
 (36, np.float64(0.09577469442737814)),
 (82, np.float64(0.09577469442737814)),
 (1650, np.float64(0.09577469442737814)),
 (104, np.float64(0.09488391758547611)),
 (1785, np.float64(0.09420123445255507)),
 (783, np.float64(0.09359606245812255)),
 (1378, np.float64(0.09008092308994009)),
 (367, np.float64(0.08968396095087

In [168]:
distance=sorted(list(enumerate(sim[2])),reverse=True,key=lambda x:x[1])
for i in distance[0:5]:
    print(i)
#it also gives us the movie from which we are looking for recommendation we can remove it ...distance[1:6] and then we can print the movie name using index

(2, np.float64(1.0))
(17, np.float64(0.42270488818560925))
(287, np.float64(0.20637643102698372))
(38, np.float64(0.17411871256445144))
(2187, np.float64(0.15608125533549166))


In [169]:
for i in distance[0:6]:
    print(movies.iloc[i[0]].Title)

Spider-Man: Across the Spider-Verse
Spider-Man: Into the Spider-Verse
Spider-Man: Homecoming
Spider-Man: No Way Home
Charlotte's Web
Thor: Ragnarok


In [170]:
def recommend(movie_name):
    movie_index=movies[movies['Title']==movie_name].index[0]
    distance=sorted(list(enumerate(sim[movie_index])),reverse=True, key=lambda x:x[1])
    for i in distance[1:6]:
        print(movies.iloc[i[0]].Title)


In [171]:
recommend('The Dark Knight Rises')

The Dark Knight
The Batman
Joker(I)
Batman Begins
Batman


In [172]:
#pickel used so that we can save our mddel and  reuse it without training the complt model each time
import pickle


In [173]:
#we neeed to save updated_movie dataset & sim_matrix
#pickle.dump(movies,open('movie_list.pkl','wb'))
pickle.dump(sim,open('sim_mtrix.pkl','wb'))

In [174]:
movies.to_csv('movies.csv',index=False)